### ISSUE TITLE
很棒的工作

### ISSUE THREAD

**Issue by moondaiy** [whai362/PSENet#1]
请问,有代码复现什么的么?对这个工作 ,我很有兴趣...期待代码和论文 进一步放出

**Comment by yangxue0827** [comment]
请问代码是基于什么深度学习框架的?

**Comment by whai362** [comment]
基于PyTorch的

**Comment by WenmuZhou** [comment]
期待代码

**Comment by RogerYu123** [comment]
很棒的工作，期待作者的代码

**Comment by rmfckaka** [comment]
期待作者的代码！

**Comment by wanghuok** [comment]
很期待作者的代码啊！

**Comment by whai362** [comment]
谢谢各位的支持，我目前在准备期刊的扩展实验，做完了我就把源码公开。

**Comment by lanfengecho** [comment]
非常非常非常非常期待作者的代码，加油

**Comment by LittleMisss** [comment]
目前正在做这部分的工作，期待源码！

**Comment by af258963** [comment]
期待

**Comment by wuyunxiangwyx** [comment]
感谢作者，期待中

**Comment by kulkarnivishal** [comment]
Looking forward to the code

**Comment by tianzhuotao** [comment]
期待代码ing，希望能够提供一个pretrain的model～

**Comment by junhocho** [comment]
The end of September is coming.

**Comment by zhoulinyuan** [comment]
自己实现一个又不难，不要等作者了

**Comment by maky-hnou** [comment]
End of October :D

**Comment by WenmuZhou** [comment]
看来出了意外了

**Comment by whai362** [comment]
Thanks for your attention. Our method is not good enough to pass the peer review. So we decide to make our method better before we open the source of our code. Sorry about that.

**Comment by WenmuZhou** [comment]
看到作者中的是cvpr2019, 预感离代码开源不久了
