### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by WenmuZhou** [whai362/PSENet#10]
在论文中，提到了
![image](https://user-images.githubusercontent.com/12406017/51455014-95f00580-1d82-11e9-8c7d-65f2fd8754d4.png)，请问这里是直接从图片中crop出640*640的图片，还是向east那样随机 crop一个区域然后进行宽高直接resize到640？

**Comment by whai362** [comment]
直接crop的

**Comment by WenmuZhou** [comment]
懂了，谢谢

**Comment by WenmuZhou** [comment]
在crop的过程中，需要保证crop出来的图片必须包含文本实例吗

**Comment by whai362** [comment]
要的

**Comment by WenmuZhou** [comment]
能给一份您的crop代码吗

**Comment by whai362** [comment]
def random_crop(imgs, img_size):
    h, w = imgs[0].shape[0:2]
    th, tw = img_size
    if w == tw and h == th:
        return imgs
    
    if random.random() > 3.0 / 8.0 and np.max(imgs[1]) > 0:
        tl = np.min(np.where(imgs[1] > 0), axis = 1) - img_size
        tl[tl < 0] = 0
        br = np.max(np.where(imgs[1] > 0), axis = 1) - img_size
        br[br < 0] = 0
        br[0] = min(br[0], h - th)
        br[1] = min(br[1], w - tw)
        
        i = random.randint(tl[0], br[0])
        j = random.randint(tl[1], br[1])
    else:
        i = random.randint(0, h - th)
        j = random.randint(0, w - tw)
    
    # return i, j, th, tw
    for idx in range(len(imgs)):
        if len(imgs[idx].shape) == 3:
            imgs[idx] = imgs[idx][i:i + th, j:j + tw, :]
        else:
            imgs[idx] = imgs[idx][i:i + th, j:j + tw]
    return imgs

**Comment by whai362** [comment]
[crop.txt](https://github.com/whai362/PSENet/files/2858583/crop.txt)

**Comment by WenmuZhou** [comment]
谢谢

**Comment by WenmuZhou** [comment]
在您的crop中，imgs[0]是指的原图像，imgs[1]是指的最大的kernel吗

**Comment by whai362** [comment]
可以这么理解吧，你可以认为，groundtruth之类的信息是和输入图片一起进行裁剪的，这样能保证一致

**Comment by YanShuang17** [comment]
作者您好，我发现random_crop()函数得到的training mask中，很多裁剪结果没有包含任何valid text instances，即train_ic15.py/ohem_single()中的pos_num的值为0，我用您的训练代码跑了10个epoch，测试部分代码以及结果如下：
```python
...
total_sample = 0
zero_sample = 0
def ohem_single(score, gt_text, training_mask):
    pos_num = (int)(np.sum(gt_text > 0.5)) - (int)(np.sum((gt_text > 0.5) & (training_mask <= 0.5)))
    print('pos_num: ', pos_num)
    global total_sample, zero_sample
    total_sample += 1
    if pos_num==0:
        zero_sample += 1
    print('black_ratio: {}/{} = {:.4f}%'.format(zero_sample, total_sample, zero_sample*100.0/total_sample))
...
```
部分打印结果如下:
```bash
...
('pos_num: ', 0)
black_ratio: 1899/9999 = 18.9919%
('pos_num: ', 17474)
black_ratio: 1899/10000 = 18.9900%

Epoch: [11 | 600] LR: 0.001000
('pos_num: ', 4287)
black_ratio: 1899/10001 = 18.9881%
('pos_num: ', 26144)
black_ratio: 1899/10002 = 18.9862%
...
```
也就是说，训练时，有接近1/5的裁剪是完全是无效的裁剪，请问您这样设置是故意为了做augmentation吗？ 期待您的解释@whai362

**Comment by xiiiiiiii** [comment]
> crop之前，保证短边大于640（如果短边小于640，等比例缩放到短边640）。
> crop会有文本实例中间切掉

crop的时候有文本被切割掉没有关系吗？不会影响到后续的检测吗？

**Comment by xiiiiiiii** [comment]
> 在crop的过程中，需要保证crop出来的图片必须包含文本实例吗

奥，我明白了，因为把标签转化成了黑白图，所以最后根据这个来计算loss，所以文本被切割掉也没有关系，是这样吧？
