### ISSUE TITLE
标注的点不一样如何训练

### ISSUE THREAD

**Issue by lijun20** [whai362/PSENet#105]
你好，如果标注的点不一样，比如有的4个，有的6个，有的8个，如何像ctw那样训练？
62,756,463,770,471,923,52,917
782,461,995,493,1003,557,772,537
692,94,808,14,957,4,1067,36,1137,82,1197,188,1131,212,1089,150,1015,96,878,72,788,114,746,158
704,311,712,367,742,409,770,443,728,479,696,445,664,403,644,313
1017,491,1073,451,1113,399,1127,375,1171,407,1149,455,1107,509,1041,539
507,766,941,788,937,925,487,925
208,1059,828,1067,824,1141,210,1135

**Comment by ChenJian7578** [comment]
首先你要知道ctw训练的时候其标签的含义，前四个值为矩形框坐标，后面的28个为mask坐标，作者在读取数据的时候将索引写死了导致你标注的点不均匀的时候可能会有问题，你可以对代码进行修改来自适应。
路径：PSENet/dataset/psenet/psenet_ctw.py     get_ann函数下
