### ISSUE TITLE
文字漏识

### ISSUE THREAD

**Issue by TyrionChou** [whai362/PSENet#115]
作者您好，我想询问一下，我在自己的训练集上训练模型后，测试，发现测试图像中会出现漏识的现象，请问您有没有什么办法减少这一问题吗？

**Comment by WenmuZhou** [comment]
单个数字比较容易漏  这是通病

**Comment by viviayi** [comment]
测试参数设置可以尝试修改，减少漏识

**Comment by TyrionChou** [comment]
主要的漏识现象，可能是字体尺度比较小，调整哪个参数可以提上效果呢？

**Comment by TyrionChou** [comment]
主要是有三个参数，分别是测试代码中的min_kernel_area，min_area，min_score

**Comment by TyrionChou** [comment]
@WenmuZhou 您好，问一下您知道测试代码中binary_th这个参数的含义吗？
