### ISSUE TITLE
测试代码有一些疑问！

### ISSUE THREAD

**Issue by TyrionChou** [whai362/PSENet#120]
代码中text = outputs[:, 0, :, :]，kernels = outputs[:, 0:args.kernel_num, :, :] * text，kernel要乘text的目的是什么呢？

**Comment by TyrionChou** [comment]
是要去除较小的kernel结果中不属于text的部分

**Comment by KosukeHao** [comment]
请问为什么在训练时用的是kernels = outputs[:, 1:, :, :]，
而测试时用的是kernels = outputs[:, 0:args.kernel_num, :, :] * text，那岂不是测试时outputs的最后一个channel完全没有用到？

**Comment by TyrionChou** [comment]
> 请问为什么在训练时用的是kernels = outputs[:, 1:, :, :]，
> 而测试时用的是kernels = outputs[:, 0:args.kernel_num, :, :] * text，那岂不是测试时outputs的最后一个channel完全没有用到？



> 请问为什么在训练时用的是kernels = outputs[:, 1:, :, :]，
> 而测试时用的是kernels = outputs[:, 0:args.kernel_num, :, :] * text，那岂不是测试时outputs的最后一个channel完全没有用到？
训练的时候要计算损失，分开计算，而测试的时候都用了。7个kernel的话，index肯定是0-6！
