### ISSUE TITLE
检测框位置偏上

### ISSUE THREAD

**Issue by viviayi** [whai362/PSENet#121]
有没有遇到训练的模型测试时检测框比实际位置有上移的情况的呢？

**Comment by congjianting** [comment]
把输入图像尺寸(H,W)做成4的倍数, 就可以解决了

**Comment by viviayi** [comment]
> 把输入图像尺寸(H,W)做成4的倍数, 就可以解决了

谢谢回复，但是我这边尝试以后好像没有效果

**Comment by congjianting** [comment]
# forward
 outputs = self._model(img)
你保证img的尺寸是可以被4整除的, 而不是scale前的图像

**Comment by congjianting** [comment]
# forward
 outputs = self._model(img)
你保证img的尺寸是可以被4整除的, 而不是scale前的图像

**Comment by viviayi** [comment]
> # forward
> outputs = self._model(img)
> 你保证img的尺寸是可以被4整除的, 而不是scale前的图像

scale前和输入图像我都有试过调整为被4整除
有采用同一张图用看图工具缩放到边长为4的倍数再输入网络，但输出还是和调整之前一样

**Comment by congjianting** [comment]
你是图中的所有目标都有向上倾向还是仅几个目标有这种向上倾向?

**Comment by viviayi** [comment]
> 你是图中的所有目标都有向上倾向还是仅几个目标有这种向上倾向?

图像下半部分的所有目标向上的比较明显，越靠近底部越明显，上半部分的目标向上的倾向比较小

**Comment by congjianting** [comment]
那应该就是这个问题,  你保证预测时, outputs = model(img)的img的size的高和宽均可被4整除, 你再试试, 你可以把图像pad成正方形来验证.

**Comment by viviayi** [comment]
> 那应该就是这个问题, 你保证预测时, outputs = model(img)的img的size的高和宽均可被4整除, 你再试试, 你可以把图像pad成正方形来验证.

嗯嗯，我今天刚刚尝试在scale的时候把图像直接resize到long_size大小的正方形，图像检测框出来是没有上移的，但是会带来形变，不知道不是正方形可不可以，我再试试

**Comment by viviayi** [comment]
> 那应该就是这个问题, 你保证预测时, outputs = model(img)的img的size的高和宽均可被4整除, 你再试试, 你可以把图像pad成正方形来验证.

检查了一下，刚刚测试输入图像直接变为4的倍数，已经是两边都变了的，但是还是会出现上移，看来确实是需要输入是正方形了

**Comment by Lanme** [comment]
请问训练的时候跑了多少的数据集和多少epoch呀

**Comment by GYxiaOH** [comment]
@congjianting 请问下这是什么原理，为什么要4的倍数

**Comment by viviayi** [comment]
> @congjianting 请问下这是什么原理，为什么要4的倍数

4的倍数没有用，我这边是padding到正方形才有用，具体原因也不太清楚

**Comment by xxlxx1** [comment]
@GYxiaOH 我感觉是因为网络最后输出是原始图片的1/4 而且取整了，如果原始图片大小不能被4整除，那么得到的框对于原始图片就会产生便宜，因为取整舍去了小数部分

**Comment by xxlxx1** [comment]
@viviayi 我试了下，32的倍数可以，不用正方形。 tf版本的psenet就是这么做的，结果没问题 https://github.com/liuheng92/tensorflow_PSENet/blob/master/eval.py  65行

**Comment by viviayi** [comment]
> @viviayi 我试了下，32的倍数可以，不用正方形。 tf版本的psenet就是这么做的，结果没问题 https://github.com/liuheng92/tensorflow_PSENet/blob/master/eval.py 65行

确实可行，多谢！

**Comment by viviayi** [comment]
> @viviayi 我试了下，32的倍数可以，不用正方形。 tf版本的psenet就是这么做的，结果没问题 https://github.com/liuheng92/tensorflow_PSENet/blob/master/eval.py 65行

不好意思我昨天测试好像有问题，我这边试了padding到32的倍数还是有偏移，我是在dataset/***_test_loader.py里的scale函数进行padding的，请问你是在哪里改的呢

**Comment by xxlxx1** [comment]
@viviayi 我是在拿到图片进网络前就reshape，然后只有展示框什么的都是用reshape之后的

**Comment by Zhang-O** [comment]
> @viviayi 我试了下，32的倍数可以，不用正方形。 tf版本的psenet就是这么做的，结果没问题 https://github.com/liuheng92/tensorflow_PSENet/blob/master/eval.py 65行

有没有比较下面两种方式的优劣：
1. 将长宽padding到32的整数倍
2. 将长宽resize到32的整数倍
