### ISSUE TITLE
关于训练和预测时kernels的获取方式不同的问题

### ISSUE THREAD

**Issue by KosukeHao** [whai362/PSENet#123]
作者您好，感谢您的工作，这里有个问题想请问一下：

请问为什么在训练时用的是kernels = outputs[:, 1:, :, :]，具体体现在train_ic15.py  的122行，

而测试时用的是kernels = outputs[:, 0:args.kernel_num, :, :] * text，具体体现在test_ic15.py的132行，

那岂不是测试时outputs的最后一个channel完全没有用到？

**Comment by fxwfzsxyq** [comment]
一共输出7个map，0 是text ，1-6是kernel ，都用到了呀

**Comment by KosukeHao** [comment]
已经解决
