### ISSUE TITLE
Wrong "help" parameter

### ISSUE THREAD

**Issue by LJXLJXLJX** [whai362/PSENet#126]
https://github.com/whai362/PSENet/blob/d5926688a531242acd5bd5b771c94d1998bac4dd/test_ic15.py#L190-L196

**Comment by TyrionChou** [comment]
do you kown mean of binary_th ?

**Comment by LJXLJXLJX** [comment]
> do you kown mean of binary_th ?

NO

**Comment by TyrionChou** [comment]
kernel_num 是和你训练的时候的kernel数量， scale是对你测试图像预测结果的缩小倍数，long_size 好像是用来调整你测试图像的最长边的大小
