### ISSUE TITLE
num_classes=7

### ISSUE THREAD

**Issue by jun214384468** [whai362/PSENet#135]
残差网络中num_classes=7这个参数是什么意思呢

**Comment by fxwfzsxyq** [comment]
最后输出7个map，就是7个分割图

**Comment by HongChow** [comment]
> 残差网络中num_classes=7这个参数是什么意思呢

我也有点费解, 如果是7个featuremap的话,不应该是在前面定义的channel数目么?

**Comment by RoseSakurai** [comment]
模型的输出shape是(batch_size, 7, img_size(0), img_size(1))

**Comment by yufanxin** [comment]
同问，我的数据集只有一个类别，我将num_classes改为1，但是运行是会报错，这里的num_classes难道不是标注的类别数吗？
