### ISSUE TITLE
In file ‘icdar2015_loader.py’      ri = 1 −(1 − m) × (n − i)/(n − 1)

### ISSUE THREAD

**Issue by zgsxwsdxg** [whai362/PSENet#137]
作者，您好！
           首先感谢您的巨大工作，和贡献代码，我在阅读您的代码时发现icdar2015_loader.py文件中
rate = 1.0 - (1.0 - self.min_scale) / (self.kernel_num - 1) * i 这句代码和论文描述的公式不一样。

您能给一些解释吗？谢谢！为什么不一样？ri = 1 −(1 − m) × (n − i)/(n − 1) ;

**Comment by NguyenViet123** [comment]
I see it too.
Thanks for explain.

**Comment by QQ1696311291** [comment]
为什么呢？

**Comment by jewelc92** [comment]
> 作者，您好！
> 首先感谢您的巨大工作，和贡献代码，我在阅读您的代码时发现icdar2015_loader.py文件中
> rate = 1.0 - (1.0 - self.min_scale) / (self.kernel_num - 1) * i 这句代码和论文描述的公式不一样。
> 
> 您能给一些解释吗？谢谢！为什么不一样？ri = 1 −(1 − m) × (n − i)/(n − 1) ;

i的取值范围是从1到n，所以i和n-i最终的结果是一样的，只是顺序反了而已
