### ISSUE TITLE
前五层结果不对

### ISSUE THREAD

**Issue by rkshuai** [whai362/PSENet#14]
你好，我使用n=6，在训练过程中发现前五层的结果不如最后一层结果的好，目前我迭代了20个epoch，是不是还需要继续迭代还是说Ls的损失写的有问题啊，Ls中的W一定要有吗？
![capture_2019129_163106](https://user-images.githubusercontent.com/11296462/51894845-d3d4d580-23e3-11e9-9b68-ec82d160cac8.jpg)
![capture_2019129_163224](https://user-images.githubusercontent.com/11296462/51894860-dcc5a700-23e3-11e9-91a1-b1ed6e13d735.jpg)
![capture_2019129_163136](https://user-images.githubusercontent.com/11296462/51894874-e4854b80-23e3-11e9-998c-2217bea4cbb7.jpg)
![capture_2019129_163149](https://user-images.githubusercontent.com/11296462/51894878-e6e7a580-23e3-11e9-8bf6-97b12c7168e6.jpg)
![capture_2019129_163158](https://user-images.githubusercontent.com/11296462/51894886-e8b16900-23e3-11e9-9f8d-54fc35d2b0c7.jpg)
![capture_2019129_163209](https://user-images.githubusercontent.com/11296462/51894890-eb13c300-23e3-11e9-8562-11f148fa4d5a.jpg)
![capture_2019129_163237](https://user-images.githubusercontent.com/11296462/51894905-f5ce5800-23e3-11e9-9100-51e043d04f9b.jpg)

**Comment by whai362** [comment]
W是要的

**Comment by rkshuai** [comment]
我的就是加了以后才这样的，把W去掉反而没问题了

**Comment by whai362** [comment]
我这边是有W，结果是稍好的。我训练ic15的话大概是600轮。4卡大概需要半天左右

**Comment by rkshuai** [comment]
我这里加上W始终不行。对于最后一层来说它能很快收敛，如果使用W，则只让前五层学到W内的东西，W外的就不再参与训练，所以造成前五层W外的结果预测时错误的，不知道我这样理解对不对？
这是我的代码：W = tf.cast(tf.greater_equal(y_pred_cls[:,:,:,TRIAN_CONFIG['n_number_scale']-1], 0.5), dtype=tf.float32)，希望您能不吝赐教。

**Comment by whai362** [comment]
你可以试试看直接用ground truth (gt)作为W。用gt作为W的直观理解是：只关心文字区域里面的kernel训练。也能达到类似的结果。

**Comment by rkshuai** [comment]
你好，我尝试了使用gt，但是依然不行。。目前我尝试以下方案好像有效果：
1. 去掉W
2. 将W的取值从1和0变为1和0.5
感觉对于前五层只让他们关心文本区域的训练的话，则对非文字区域不能很好的预测。

**Comment by whai362** [comment]
好奇怪，我这边没有碰到过这个问题。大概第2和第3个epoch就开始收敛了。

噢，对了，有一个比较关键的事情，就是这边会预测text和kernel，
在后处理的时候，对于kernel，会有一样乘上一个W，里面也只有0和1，这个W是根据text算的，text里面得分>0.5的pixel在W里面是1，否则是0。这样kernel就不用关心非文本区域了。

**Comment by whai362** [comment]
给你提供一份我resnet50训练的日志吧，里面IOU_t是text区域的iou，IOU_k是最小kernel的iou（只关心W里面值为1的pixel）

[log.txt](https://github.com/whai362/PSENet/files/2817470/log.txt)

**Comment by rkshuai** [comment]
好的，非常感谢，我觉得应该就是您说的在后处理的时候也要乘以W的原因。
我之前没做这个处理，然后在训练过程中又发现前五层对于W外的区域没有预测准确，然后就一直觉得是前五层没预测好。

**Comment by rkshuai** [comment]
请问您说的w是指最后一层的w吧





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by wulouzhu** [comment]
@whai362 您好，我看了你的log.txt，我用自己的数据进行训练，我的Acc_t和IOU_t跟你差不多，但我的IOU_k总是在0.8左右就上不去了，请问有可能是什么问题呢？谢谢
