### ISSUE TITLE
python3.6版本的pse c++模块，需改那些地方，才能make成功

### ISSUE THREAD

**Issue by zgsxwsdxg** [whai362/PSENet#142]
您好！感谢你巨大的工作和共享精神。想请教您，python3.6版本的pse c++模块，需改那些地方，才能make成功？谢谢！期待您的回复

**Comment by EricHuiK** [comment]
改好了么

**Comment by RoseSakurai** [comment]
python3版本已经发布，感兴趣的话请关注！
新版本中只需bash compile.sh
