### ISSUE TITLE
progressive scale expansion algorithm

### ISSUE THREAD

**Issue by WenmuZhou** [whai362/PSENet#15]
Can you open source the progressive scale expansion algorithm alone？

**Comment by whai362** [comment]
PSE is based on breadth-first search. The python code is [pse.txt](https://github.com/whai362/PSENet/files/2910309/pse.txt). The python code is just easy to read. For high efficiency, you can use c++ to implement it.

**Comment by chengjc2019** [comment]
I have tried to train the model without modifing any parameter. However, the results are not correct, generating too many boxes even filling the pictures.I don't konw how to solve this problem.

**Comment by RoseSakurai** [comment]
You can check the config file in config/psenet/
