### ISSUE TITLE
python3.6的跑不起来....

### ISSUE THREAD

**Issue by HongChow** [whai362/PSENet#152]
先是 
include/pybind11/detail/common.h:113:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [adaptor.so] Error 1
这个错误
Makefile:10: recipe for target 'adaptor.so' failed

**Comment by xiao12mm** [comment]
linux下跑

**Comment by HongChow** [comment]
> linux下跑

一直用的Ubuntu

**Comment by HongChow** [comment]
3.6下面好像也是有这个头文件的:
(base) hong@ZM:/usr/include/python3.6$ ll Python.h 
-rw-r--r-- 1 root root 3221 4月  18 09:56 Python.h

**Comment by fxwfzsxyq** [comment]
common.h这个文件有三行修改一下就行

**Comment by HongChow** [comment]
> common.h这个文件有三行修改一下就行

改好了，改成了python的安装对应的头文件

**Comment by RoseSakurai** [comment]
现在有python3版本啦，感兴趣的请关注。
