### ISSUE TITLE
作者提供的tar模型压缩包为什么我一个都打不开，全都显示损坏？

### ISSUE THREAD

**Issue by pingzi5233** [whai362/PSENet#156]
如题，请问有人遇到这个情况吗？
是我下载错了还是解压方式不对呢？
百度云下载

**Comment by fxwfzsxyq** [comment]
这个就是模型你解压它干啥。。。。。。

**Comment by fxwfzsxyq** [comment]
> 如题，请问有人遇到这个情况吗？
> 是我下载错了还是解压方式不对呢？
> 百度云下载
这个就是模型，你解压他干啥。。。

**Comment by amdslgl** [comment]
模型没有错，只是因为这tar文件不需要解压，只需要用model=torch.load('tar path')

**Comment by qiuyuenheng** [comment]
> 模型没有错，只是因为这tar文件不需要解压，只需要用model=torch.load('tar path')

原来是这样！感谢！！

**Comment by ckqsars** [comment]
你好，百度云的下载链接在哪里可以找到 google drive的已经不能用了
