### ISSUE TITLE
请教下long size

### ISSUE THREAD

**Issue by xmy0916** [whai362/PSENet#171]
您好～感谢您提供的论文以及代码，请教一下您paper的配置文件设置的long size2240是直接改了data -> train -> short_size = 2240吗

**Comment by whai362** [comment]
新代码统一使用short_size了，long_size 2240等效于short_size 1260。
另外修改short_size直接在配置文件的data里修改就行。
https://github.com/whai362/PSENet/blob/python3/config/psenet/psenet_r50_ic15_1024.py

**Comment by xmy0916** [comment]
@whai362 谢谢～
