### ISSUE TITLE
有关adaptor.so: undefined symbol: _Py_ZeroStruct的错误

### ISSUE THREAD

**Issue by zzdang** [whai362/PSENet#23]
您好，用makefile编译完adaptor.so后，调用会报错“undefined symbol: _Py_ZeroStruct”，是怎么回事呀？
你们有遇到吗？
谢谢

**Comment by WenmuZhou** [comment]
py2没问题

**Comment by zzdang** [comment]
有用python3遇到这个错该怎么解决，求助呀

**Comment by WenmuZhou** [comment]
参考这个makefile
https://github.com/WenmuZhou/PSENet.pytorch/blob/master/author_pse/Makefile

**Comment by WeihongM** [comment]
@whai362 @WenmuZhou 
Hello， I met also make error, I can compile the adaptor.so alone successsfully, However when I want to import the .so file into python file, it throw the error.
`ImportError: /opt/intel/mkl/lib/intel64/libmkl_sequential.so: undefined symbol: mkl_sparse_s_a
dd_ker1_i8`

>Environment:
>python2.7

**Comment by OuYag** [comment]
@whai362 @WenmuZhou
请问下，安装在conda虚拟环境目录下的opencv3如何修改MakeFile文件？

**Comment by OuYag** [comment]
@whai362 @WenmuZhou
adaptor.so编译成功,但是import pse报错：
Traceback (most recent call last):
  File "test_ic15.py", line 19, in <module>
    from pse import pse
  File "/mnt/home/ouyanggu/PSENet/PSENet_pytorch/pse/__init__.py", line 11, in <module>
    from .adaptor import pse as cpse
ImportError: /mnt/home/PSENet/pse/adaptor.so: undefined symbol: _ZN2cv8fastFreeEPv

请问有没有解决办法？谢谢。

**Comment by rkshuai** [comment]
@zzdang 修改pse/include/pybind11/detail/common.h中的第112~114：
#include <python2.7/Python.h>
#include <python2.7/frameobject.h>
#include <python2.7/pythread.h>
为：
#include <Python.h>                                                                                                                                                                                               
#include <frameobject.h>                                                                                                                                                                                          
#include <pythread.h>

**Comment by tangsipeng** [comment]
@zzdang  请问最后解决了吗？我也遇到这个问题

**Comment by zzdang** [comment]
@tangsipeng ，按照rkshuai 说的，可以解决问题

**Comment by tangsipeng** [comment]
@zzdang  谢谢，我也解决了。测试速度只有1fps，你呢？

**Comment by wangshuai66666** [comment]
请问 我按照rkshuai 说的改完后，有报错说Python.h 找不到怎么办，我安装了anaconda3

**Comment by wangshuai66666** [comment]
> 请问 我按照rkshuai 说的改完后，有报错说Python.h 找不到怎么办，我安装了anaconda3 @zzdang

**Comment by wangshuai66666** [comment]
> @zzdang 谢谢，我也解决了。测试速度只有1fps，你呢？

我的fps才0.65呢  GPU K40c 12G

**Comment by QQ1696311291** [comment]
> @zzdang 修改pse/include/pybind11/detail/common.h中的第112~114：
> #include <python2.7/Python.h>
> #include <python2.7/frameobject.h>
> #include <python2.7/pythread.h>
> 为：
> #include <Python.h>
> #include <frameobject.h>
> #include <pythread.h>

**Comment by QQ1696311291** [comment]
请问改变之后运行报错没有Python.h这个文件目录

**Comment by QQ1696311291** [comment]
怎么办

**Comment by Tian14267** [comment]
请问你python3编译成功了吗？我的一直报错啊。可以有空帮忙看一下吗
#88[https://github.com/whai362/PSENet/issues/88](url)
@zzdang @tangsipeng @WenmuZhou @WeihongM

**Comment by FredlinT** [comment]
> @zzdang 修改pse/include/pybind11/detail/common.h中的第112~114：
> #include <python2.7/Python.h>
> #include <python2.7/frameobject.h>
> #include <python2.7/pythread.h>
> 为：
> #include <Python.h>
> #include <frameobject.h>
> #include <pythread.h>

我改完之后，遇到了include/pybind11/detail/common.h:116:20: fatal error: Python.h: No such file or directory的问题

**Comment by jacoc** [comment]
> > @zzdang 修改pse/include/pybind11/detail/common.h中的第112~114：
> > #include <python2.7/Python.h>
> > #include <python2.7/frameobject.h>
> > #include <python2.7/pythread.h>
> > 为：
> > #include <Python.h>
> > #include <frameobject.h>
> > #include <pythread.h>
> 
> 我改完之后，遇到了include/pybind11/detail/common.h:116:20: fatal error: Python.h: No such file or directory的问题

同样的问题，解决了吗？

**Comment by Tian14267** [comment]
> > @zzdang 修改pse/include/pybind11/detail/common.h中的第112~114：
> > #include <python2.7/Python.h>
> > #include <python2.7/frameobject.h>
> > #include <python2.7/pythread.h>
> > 为：
> > #include <Python.h>
> > #include <frameobject.h>
> > #include <pythread.h>
> 
> 我改完之后，遇到了include/pybind11/detail/common.h:116:20: fatal error: Python.h: No such file or directory的问题

请问你解决了吗？我也遇到Python.h: No such file or directory的问题。请问怎么解决？

**Comment by Tian14267** [comment]
> > > @zzdang 修改pse/include/pybind11/detail/common.h中的第112~114：
> > > #include <python2.7/Python.h>
> > > #include <python2.7/frameobject.h>
> > > #include <python2.7/pythread.h>
> > > 为：
> > > #include <Python.h>
> > > #include <frameobject.h>
> > > #include <pythread.h>
> > 
> > 
> > 我改完之后，遇到了include/pybind11/detail/common.h:116:20: fatal error: Python.h: No such file or directory的问题
> 
> 同样的问题，解决了吗？

请问你解决了嘛

**Comment by Tian14267** [comment]
问题已经解决。在用python3编译的时候，需要确定自己的python是具体哪个版本。python3.5，还是python3.6。具体可以查看路径：/usr/include/ 在这个文件夹内找python的文件（python2.7或者python3.5）。然后按照下面方法修改：
修改pse/include/pybind11/detail/common.h中的第112~114：
#include <python2.7/Python.h>
#include <python2.7/frameobject.h>
#include <python2.7/pythread.h>
为：
#include <python3.5/Python.h>
#include <python3.5/frameobject.h>
#include <python3.5/pythread.h>

因为我的python是3.5版本。具体可以根据自己的版本修改。需要用到的"Python.h"、“frameobject.h”、“pythread.h”都在/usr/include/python3.5/ 这个文件夹里面。改完之后编译就ok了。
