### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by jiaying96** [whai362/PSENet#28]
使用训练好的模型测试

CUDA_VISIBLE_DEVICES=0 python test_ctw1500.py --scale 1 --resume ./model/ctw1500_res50_pretrain_ic17.pth.tar

![image](https://user-images.githubusercontent.com/16167043/55709846-d3783c80-5a1b-11e9-8aa1-7bc384fcf235.png)

**Comment by whai362** [comment]
use opencv-python3.4

**Comment by jiaying96** [comment]
@whai362 thank you ,problem solved
