### ISSUE TITLE
A mistake about scale

### ISSUE THREAD

**Issue by jhl13** [whai362/PSENet#33]
in test_ic15.py
line 143,scale = (org_img.shape[0] * 1.0 / pred.shape[0], org_img.shape[1] * 1.0 / pred.shape[1])
it maybe wrong?
shape[0]->h
shape[1]->w
so, I think it is 
scale = (org_img.shape[1] * 1.0 / pred.shape[1], org_img.shape[0] * 1.0 / pred.shape[0]) @whai362

**Comment by whai362** [comment]
Fixed it. Thank you very much!
I mistake them in "test_ic15.py" and "test_ctw1500.py", but they make no change to the final results because I keep the scale of w and h is same when testing.
