### ISSUE TITLE
Pretrained model "resnet101"

### ISSUE THREAD

**Issue by jhl13** [whai362/PSENet#43]
when train with option --arch='resnet101',error raised
File "/root/data/workspace/PSENet/models/fpn_resnet.py", line 477, in resnet101
  pretrained_model = model_zoo.load_url(model_urls['resnet101'])
File "/usr/local/lib/python2.7/dist-packages/torch/utils/model_zoo.py", line 65, in load_url
  hash_prefix = HASH_REGEX.search(filename).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Is the link invalid?

**Comment by Annihilation7** [comment]
the website is false.
please use:   'resnet101': 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'

**Comment by jhl13** [comment]
> the website is false.
> please use: 'resnet101': 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'

Thank you every much!
