### ISSUE TITLE
为什么在测试的时候要把图片resize到那么大呀，2000多。。

### ISSUE THREAD

**Issue by Annihilation7** [whai362/PSENet#46]
不是特别理解，还请大佬指导，明明训练的时候根本没这么大的图- -

**Comment by Annihilation7** [comment]
效果确实很好，就是有点慢。。在1s模式下，一张图要40秒- - 我的天

**Comment by WenmuZhou** [comment]
放大之后对小目标的检测会变的更好

**Comment by Annihilation7** [comment]
> 放大之后对小目标的检测会变的更好

但是放大之后，我单卡 1s 的情况下一张图跑40秒。。 用的python版的pse算法。。但是这也太慢了吧- -

**Comment by WenmuZhou** [comment]
估计你的图片的文字区域比较多，并且python本来就不快，建议使用cpp版本的pse算法

**Comment by Annihilation7** [comment]
> 估计你的图片的文字区域比较多，并且python本来就不快，建议使用cpp版本的pse算法

文字区域普遍在30个左右，慢的离谱，好的，我尝试用一下c++版本的pse算法～谢啦

**Comment by wangshuai66666** [comment]
> > 估计你的图片的文字区域比较多，并且python本来就不快，建议使用cpp版本的pse算法
> 
> 文字区域普遍在30个左右，慢的离谱，好的，我尝试用一下c++版本的pse算法～谢啦

我用那个tensorflow版本的，速度还可以。

**Comment by Annihilation7** [comment]
> > > 估计你的图片的文字区域比较多，并且python本来就不快，建议使用cpp版本的pse算法
> > 
> > 
> > 文字区域普遍在30个左右，慢的离谱，好的，我尝试用一下c++版本的pse算法～谢啦
> 
> 我用那个tensorflow版本的，速度还可以。

哦哦，还是心来官方呀～哈哈  速度这方面我再看看吧，应该问题不大，谢啦

**Comment by bkwwangjie** [comment]
为什么我一用c++版本的pse就出现段错误（吐核）的错误呢，请问你们有这种情况吗，还有c++版本的会提升多少速度呢

**Comment by xxlxx1** [comment]
@bkwwangjie 应该是没编译成功才会这样

**Comment by Annihilation7** [comment]
> 估计你的图片的文字区域比较多，并且python本来就不快，建议使用cpp版本的pse算法

事实证明pypse确实慢。。。。

**Comment by ltm920716** [comment]
@bkwwangjie 请问你的问题解决了么，是因为编译PSE没有通过么？我也报了段错误，可是编译没什么问题呀

**Comment by Wini1680** [comment]
@Annihilation7 你好，请教一下，我跑的python版的pse测试单张图片最后在(torch.sign(outputs-args.binary_th)+1)/2的时候输出都是0了，这是什么原因呢？

**Comment by RoseSakurai** [comment]
Please check new python3 version. Thanks for your attention!
