### ISSUE TITLE
about random_crop()

### ISSUE THREAD

**Issue by YanShuang17** [whai362/PSENet#60]
作者您好，我发现random_crop()函数得到的training mask中，很多裁剪结果没有包含任何valid text instances，即train_ic15.py/ohem_single()中的pos_num的值为0，我用您的训练代码跑了10个epoch，测试部分代码以及结果如下：
```python
...
total_sample = 0
zero_sample = 0
def ohem_single(score, gt_text, training_mask):
    pos_num = (int)(np.sum(gt_text > 0.5)) - (int)(np.sum((gt_text > 0.5) & (training_mask <= 0.5)))
    print('pos_num: ', pos_num)
    global total_sample, zero_sample
    total_sample += 1
    if pos_num==0:
        zero_sample += 1
    print('black_ratio: {}/{} = {:.4f}%'.format(zero_sample, total_sample, zero_sample*100.0/total_sample))
...
```
部分打印结果如下:
```bash
...
('pos_num: ', 0)
black_ratio: 1899/9999 = 18.9919%
('pos_num: ', 17474)
black_ratio: 1899/10000 = 18.9900%

Epoch: [11 | 600] LR: 0.001000
('pos_num: ', 4287)
black_ratio: 1899/10001 = 18.9881%
('pos_num: ', 26144)
black_ratio: 1899/10002 = 18.9862%
...
```
也就是说，训练时，有接近1/5的裁剪是完全是无效的裁剪，请问您这样设置是故意为了做augmentation吗？ 期待您的解释@whai362

**Comment by xiiiiiiii** [comment]
你好，我想问一下为什么要进行剪裁？剪裁了的话，图片上的字不就是不完整了吗？

**Comment by YanShuang17** [comment]
你好，裁剪是为了做数据增强。仅从裁剪之后的图像块来看，就算其中部分单词被切掉一部分，剩下的还是文字区域，模型还是应该把它检测出来。不矛盾的，这样还能从一定程度增加模型的鲁棒性... @xiiiiiiii

**Comment by YanShuang17** [comment]
不过我后面简单修改了一下crop函数:
```python
def random_crop_v2(imgs, img_size):
    h, w = imgs[0].shape[0:2]
    th, tw = img_size
    if w == tw and h == th:
        return imgs

    cnt = 0
    while cnt<100:
        i = random.randint(0, h - th)
        j = random.randint(0, w - tw)
        gt_text = imgs[1][i:i + th, j:j + tw].copy()
        training_mask = imgs[2][i:i + th, j:j + tw].copy()
        valid_gt_text = gt_text * training_mask
        if valid_gt_text.sum()>100:
            for idx in range(len(imgs)):
                if len(imgs[idx].shape) == 3:
                    imgs[idx] = imgs[idx][i:i + th, j:j + tw, :]
                else:
                    imgs[idx] = imgs[idx][i:i + th, j:j + tw]
            return imgs
        else:
            cnt += 1
    # when crop attempt failed, use the whole img
    for idx in range(len(imgs)):
        imgs[idx] = cv2.resize(imgs[idx], dsize=(tw, th))
    return imgs
```
两个版本训练得到的fscore仅相差了0.2.

**Comment by Sanster** [comment]
@YanShuang17 还好，你训的模型用的什么数据集？最后能到到 85% 的 fscore 么？我在 icdar15 和  MLT 2017 上训练才 75% fscore

**Comment by YanShuang17** [comment]
你好，我简化了部分代码，以便支持python3.5。完全按照论文的配置:
仅在ic15上训练，最终在ic15测试集上的P/R/F：
* resnet50: 0.866/0.774/0.817

在ic17mlt上预训练+ic15微调。最终在ic15测试集上的P/R/F：
* resnet50: 0.879/0.811/0.844。
* resnet152: 0.888/0.780/0.831。

不清楚为啥Recall这么低，而且resnet152的效果比resnet50差，目前还在找原因，可能某些代码改的有问题。 @Sanster 供参考

**Comment by xiiiiiiii** [comment]
> 你好，我简化了部分代码，以便支持python3.5。完全按照论文的配置:
> 仅在ic15上训练，最终在ic15测试集上的P/R/F：
> 
> * resnet50: 0.866/0.774/0.817
> 
> 在ic17mlt上预训练+ic15微调。最终在ic15测试集上的P/R/F：
> 
> * resnet50: 0.879/0.811/0.844。
> * resnet152: 0.888/0.780/0.831。
> 
> 不清楚为啥Recall这么低，而且resnet152的效果比resnet50差，目前还在找原因，可能某些代码改的有问题。 @Sanster 供参考

问一下博主，是训练了多少个epoch之后达到了这个准确率，我现在训练了24个epoch，准确率是56%这个正常吗？

**Comment by Sanster** [comment]
@YanShuang17 你是跑完了 600 个 epoch 么？我是直接用 MLT + ic15 的一起训了，可能有问题，我试试完全用 ic15 训

**Comment by YanShuang17** [comment]
你好，我没跑过RCTW-17所以不清楚。 @xiiiiiiii

**Comment by YanShuang17** [comment]
先在ic17mlt上预训练，再在ic15上微调。 @Sanster

**Comment by Whu-wxy** [comment]
请问你在测试的时候，IOU_CONSTRAINT和AREA_PRECISION_CONSTRAINT有修改吗？
