### ISSUE TITLE
ls_loss的疑问

### ISSUE THREAD

**Issue by xiaomaxiao** [whai362/PSENet#7]
ignore the pixels of non-text region in the segmentation result Sn to avoid a certain
redundancy. 

其中用到 Sn > 0.5 的参与计算，但是前期Sn应该预测不到结果，那么ls_loss岂不是为0？
是否有更多的细节？

**Comment by whai362** [comment]
你说的0的情况有可能出现，所以前面kernel的loss可能会有振荡。但是，文字区域分割部分前面收敛比较快，总loss大概10次迭代后就比较稳定了

**Comment by xiaomaxiao** [comment]
我把  W = Sn > 0.5 与 真实标签区域(G)的 mask 做了并集 ，这样在前期 W=0的时候可以用 G mask 算loss，
目前训练还算稳定
