### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ltm920716** [whai362/PSENet#75]
hello!
I run tne test_ic15.py  with C++ pse cversion: 
CUDA_VISIBLE_DEVICES='5' python test_ic15.py --scale 1 --resume /home/ltm/PSENet-master/ic15_res50.pth

then:
make: Entering directory `/home/ltm/PSENet-master/PSENet-master/pse'
make: `adaptor.so' is up to date.
make: Leaving directory `/home/ltm/PSENet-master/PSENet-master/pse'
Loading model and optimizer from checkpoint '/home/ltm/PSENet-master/ic15_res50.pth'
Loaded checkpoint '/home/ltm/PSENet-master/ic15_res50.pth' (epoch 600)
progress: 0 / 500
/usr/local/python3/lib/python3.6/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/local/python3/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Segmentation fault

besides，the python pse version is ok

please help, thanks

**Comment by Pursuer1030** [comment]
Have you resolved this problem? I'm in the same case.

**Comment by ltm920716** [comment]
@Pursuer1030 hello, this problem should be caused by compile environment. I make a new clear docker environment used python3, and is OK

**Comment by wulouzhu** [comment]
@ltm920716 
Can you show me your dockerfile or have you pushed the docker image to the docker hub?
