### ISSUE TITLE
kernel num is different in train and test

### ISSUE THREAD

**Issue by dedety2** [whai362/PSENet#79]
Hi，awesome wrok！I find the kernel num is different in python scripy（eg. 7 in train_ctw ,3 in test_ctw）. And I try to modify the value to the same ( 7 ) , then the eval performance drop. Is there some guide to set the kernel num in testing?

**Comment by whai362** [comment]
Thanks for your attention.
In the training phase, a large kernel num can help to cover most scales, such as 0.4, 0.5, 0.6, 0.7.
In the testing phase, we can choose a suitable min kernel scale by adjusting kernel num.

**Comment by dedety2** [comment]
Thanks, it helps a lot.
