### ISSUE TITLE
RuntimeError: Cannot compile pse: /home/shakey/deep-learning/PSENet/pse

### ISSUE THREAD

**Issue by cuimiao187561** [whai362/PSENet#82]

**Comment by honghande** [comment]
CXXFLAGS = -I include  -std=c++11 -O3 -I /home/whj/anaconda3/envs/PSENet/include

DEPS = lanms.h $(shell find include -xtype f)
CXX_SOURCES = adaptor.cpp include/clipper/clipper.cpp
#OPENCV = `pkg-config --cflags --libs opencv`
OPENCV=/home/whj/anaconda3/envs/PSENet/lib/
-Wl,-rpath = LIB_SO = adaptor.so
#LIB_SO = adaptor.so

$(LIB_SO): $(CXX_SOURCES) $(DEPS)
	$(CXX) -o $@ $(CXXFLAGS) $(LDFLAGS) $(CXX_SOURCES) --shared -fPIC $(OPENCV)

clean:
	rm -rf $(LIB_SO)

**Comment by honghande** [comment]
我是按照上述进行makefile的
你可以试试

**Comment by cuimiao187561** [comment]
谢谢，你改完以后能成功编译吗？

**Comment by honghande** [comment]
可以

------------------ Original ------------------

**Comment by cuimiao187561** [comment]
python2.7 opencv3.4.0 但是，我在make出现这个问题：
[shakey@localhost pse]$ make 
g++ -o adaptor.so -I include  -std=c++11 -O3  adaptor.cpp include/clipper/clipper.cpp --shared -fPIC `pkg-config --cflags --libs opencv`
adaptor.cpp: In function ‘void pse_adaptor::growing_text_line(std::vector<cv::Mat>&, std::vector<std::vector<int> >&, float)’:
adaptor.cpp:35:86: error: ‘connectedComponents’ was not declared in this scope
         int label_num = connectedComponents(kernals[kernals.size() - 1], label_mat, 4);
                                                                                      ^
In file included from include/pybind11/pytypes.h:12:0,
                 from include/pybind11/cast.h:13,
                 from include/pybind11/attr.h:13,
                 from include/pybind11/pybind11.h:43,
                 from adaptor.cpp:1:
adaptor.cpp: In function ‘PyObject* pybind11_init_wrapper()’:
include/pybind11/detail/common.h:261:20: warning: ‘PyObject* pybind11_init()’ is deprecated (declared at adaptor.cpp:120): PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE [-Wdeprecated-declarations]
             return pybind11_init();                                            \
                    ^
adaptor.cpp:120:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
 PYBIND11_PLUGIN(adaptor) {
 ^
include/pybind11/detail/common.h:261:34: warning: ‘PyObject* pybind11_init()’ is deprecated (declared at adaptor.cpp:120): PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE [-Wdeprecated-declarations]
             return pybind11_init();                                            \
                                  ^
adaptor.cpp:120:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
 PYBIND11_PLUGIN(adaptor) {
 ^
make: *** [adaptor.so] Error 1

**Comment by mengmeng716** [comment]
@cuimiao187561 Have you resolved this problem? I'm in the same case.

**Comment by hetianduan** [comment]
> 我是按照上述进行makefile的
> 你可以试试

你好，我按您的进行了makefile,然后报错No module named adaptor，您遇到过吗

**Comment by hetianduan** [comment]
> 我是按照上述进行makefile的
> 你可以试试

您好，我按照您上面的修改的makefile,make之后没法生成adaptor.so,显示rm -rf 是什么情况呢 我也是在anaconda3下

**Comment by ztoString** [comment]
@hetianduan 老哥，现在怎么说，我遇到了一样的问题

**Comment by hetianduan** [comment]
> @hetianduan 老哥，现在怎么说，我遇到了一样的问题



> @hetianduan 老哥，现在怎么说，我遇到了一样的问题

Contact QQ 529744208

**Comment by hetianduan** [comment]
> @hetianduan 老哥，现在怎么说，我遇到了一样的问题

Contact QQ 529744208

**Comment by loralyc** [comment]
@hetianduan 请问下您解决问题了吗，我make之后同样也是显示rm -rf

**Comment by Shualite** [comment]
Please install Opencv3.4(C++ Version) and opencv-python==3.4.3.8 together.

**Comment by skye95git** [comment]
@hetianduan  I meet the same problem with you ,print"rm -rf ",can you tell me how to solve this problem?

**Comment by AmberMsy** [comment]
I also meet the same error when compiling and got ‘rm -rf ’. No need to modify the Makefile, just install Opencv3.4(C++ Version)
