### ISSUE TITLE
我测试的结果如下图，怎么不是检测出来的区域怎么不是多边形，而是矩形

### ISSUE THREAD

**Issue by hande6688** [whai362/PSENet#83]
![2](https://user-images.githubusercontent.com/29244715/61053601-6c09c880-a420-11e9-8b4b-6c4e2f0dcd8b.JPG)

**Comment by czweb2017** [comment]
兄弟你是怎么跑起来的 我一打开一堆报错

**Comment by whai362** [comment]
文件
https://github.com/whai362/PSENet/blob/master/test_ctw1500.py
169-171行是可以得到多边形结果的，你应该跑的是test_ic15.py的结果
