### ISSUE TITLE
Why do you use training_mask?

### ISSUE THREAD

**Issue by sungreong** [whai362/PSENet#94]
Thank you for opening a good paper and code.
I have some questions.
When I looked at the data, I found that part # was in a place where the letters were rotated or where there was a problem.
If there is a # among labeling, we have confirmed that it is handled separately at icdar2015_loader.get_bboxes.
The function __getitem__ confirmed that there is a separate training_mask for that part.
And when I actually did the calculations, I understood that I only calculate with data that is not labeled #. (train_ic15 , cal_text_score)
Can you tell me why?
With the exception of #, is it because it is not a normal letter?

**Comment by RoseSakurai** [comment]
Because # means the text is not clear. So we use training_mask to ignore them.
