### ISSUE TITLE
any way to speed up the progressive scae expansion algorithm?

### ISSUE THREAD

**Issue by yyjabiding** [whai362/PSENet#96]
thanks for your great work and I found that as the number of text area increses, the progressive sacle expansion part consumes a lot of time.
any advice to speed up the part?

**Comment by fujingling** [comment]
I have the same problem.do you have any idea?@yyjabiding

**Comment by yyjabiding** [comment]
I found that the calculation of for loop part is preformed on cpu(data.cpu().numpy),it slows down a lot as the number of text line incerases, you can put the tensor on cuda and replace the numpy operation with torch operation which may speed up the procedure significantly.

**Comment by fujingling** [comment]
@yyjabiding thank you so much，Can you show me the code？

**Comment by fujingling** [comment]
I found that the function cv2.findContours() take a lot of time.

**Comment by hetianduan** [comment]
> I have the same problem.do you have any idea?@yyjabiding

你好，请问你解决了吗

**Comment by RoseSakurai** [comment]
Try the new python3 version!
